version: '3.8'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
      - /app/node_modules
    working_dir: /app
